Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
my_group = symd.load_group(11, dim=2)

print(my_group.lattice)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m my_group [38;5;241m=[39m [43msymd[49m[38;5;241;43m.[39;49m[43mload_group[49m[43m([49m[38;5;241;43m11[39;49m[43m,[49m[43m [49m[43mdim[49m[38;5;241;43m=[39;49m[38;5;241;43m2[39;49m[43m)[49m
[1;32m      3[0m [38;5;28mprint[39m(my_group[38;5;241m.[39mlattice)

File [0;32m/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/symd/groups.py:517[0m, in [0;36mload_group[0;34m(gnum, dim)[0m
[1;32m    507[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    508[0m [38;5;124;03mLoad one of the 2D planar groups or 3D space groups that tile space. The :obj:`Group`[39;00m
[1;32m    509[0m [38;5;124;03mcontains the name of the Bravais lattice, the general positions,[39;00m
[0;32m   (...)[0m
[1;32m    514[0m [38;5;124;03m:return: The :obj:`Group`[39;00m
[1;32m    515[0m [38;5;124;03m"""[39;00m
[1;32m    516[0m gnum [38;5;241m=[39m [38;5;28mstr[39m(gnum)
[0;32m--> 517[0m [38;5;28;01mfrom[39;00m [38;5;21;01mimportlib_resources[39;00m [38;5;28;01mimport[39;00m files
[1;32m    518[0m [38;5;28;01mimport[39;00m [38;5;21;01msymd[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdata[39;00m
[1;32m    520[0m fp [38;5;241m=[39m files(symd[38;5;241m.[39mdata)[38;5;241m.[39mjoinpath([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mdim[38;5;132;01m}[39;00m[38;5;124mdgroups.json[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'importlib_resources'

